---
title: "JLEWIS Final Project"
author: "Jenn Lewis"
date: "2/26/2019"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(gghighlight)
library(tidyverse)
library(dplyr)
library(rio)
library(here)
library(ggrepel)



data1 <- import(here("data", "Full_Data.csv")) 

```



```{r Figure 1}
#Show Heart Rate Data Over Time for Two Groups

#Convert Group to Factor
data1$Group <- as.factor(data1$Group)

data1$Group <- recode(data1$Group, '1' = "Control Group", '2' = "BPD Group")

#Clean Data to proper format
HRV1 <- data1 %>%
  gather(key = HRV_Segment, value = RSA, RSA_1, RSA_2, RSA_3, RSA_4, RSA_5, RSA_6, RSA_7, RSA_8, na.rm =TRUE) %>%
  select(HRV_Segment, RSA, Group) %>%
  filter(Group != "NA") %>%
  group_by(Group, HRV_Segment) %>%
  summarise(RSA = mean(RSA)) %>%
  mutate(HRV_Segment = recode(HRV_Segment,
                              "RSA_1" = "1",
                              "RSA_2" = "2",
                              "RSA_3" = "3",
                              "RSA_4" = "4",
                              "RSA_5" = "5",
                              "RSA_6" = "6",
                              "RSA_7" = "7",
                              "RSA_8" = "8"))

#Plot graph, want it to be a line graph, but doesn't show up for some reason - points show up when I use geom_point but don't know why it isn't working with geom_line
HRV1 %>%
  ggplot(aes(HRV_Segment, RSA)) +
  geom_line(aes(color = Group)) +
  theme_minimal () +
  #ylim(0, 7) +
  labs(y = "HRV",
       x = "Segment",
       title = "HRV across Time for BPD vs Control Group")

```


```{r Figure 2}
#Convert scores to standardized scores
data1 <- data1 %>%
  mutate(HAMA_C = scale(HAMA, center = TRUE, scale = TRUE),
         PHQ_C = scale(PHQ, center = TRUE, scale = TRUE),
         DERS_C = scale(DERS, center = TRUE, scale = TRUE))

#cleaning data
Symptoms <- data1 %>%
  gather(key = Symptom, value = Score, HAMA_C, PHQ_C, DERS_C, na.rm = TRUE) %>%
  mutate(Symptom = recode(Symptom, 
                           "HAMA_C" = "Anxiety",
                           "PHQ_C" = "Depression",
                           "DERS_C" = "Emotion Dysregulation")) %>%
  group_by(Group, Symptom) %>%
  summarise(Score = mean(Score)) %>%
  filter(Group != "NA")
  

#Plot to show Mental Health Profile of Groups
Symptoms %>%
  ggplot(aes(Symptom, Score, fill = Group)) +
  geom_col(position = "dodge") +
  scale_fill_viridis_d() +
  labs(title = "Mental Health Profiles of Clinical and Non-Clinical Samples",
       x = "Symptom",
       y = "Score (standardized)")

```

```{r Figure 3}




```
